version: '3'

services:

  app-invoice:
    image: arturodiaz02/app-invoice:v1
    container_name: app-invoice
    platform: linux/amd64
    ports:
      - "8006:8006"
    networks:
      - distribuidos

networks:
   distribuidos:
     external: true